services:
  neo4j:
    container_name: neo4j_finbench
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7689:7689
    environment:
      - NEO4J_server_memory_heap_initial__size=6G
      - NEO4J_server_memory_heap_max__size=6G
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./import:/var/lib/neo4j/import
      - ./scripts:/var/lib/neo4j/scripts
    command: >
      bash -c "
      neo4j start &&
      echo 'Waiting for Neo4j to be ready...' &&
      until cypher-shell --format plain 'RETURN 1' > /dev/null 2>&1; do
        echo 'Waiting...';
        sleep 5;
      done;
      echo 'Neo4j is ready. Starting data import...' &&
      cypher-shell --format plain < /var/lib/neo4j/scripts/init.cypher &&
      echo 'Data import completed.' &&
      neo4j console"
